version: "3.9"
services:
        elonbot:
                build: .
                volumes:
                        - ./log:/usr/src/elonbot/log:z
                        - ./auth:/usr/src/elonbot/auth:ro
                        - ./scraplist.json:/usr/src/elonbot/scraplist.json:ro
                restart: always
                init: true
                cap_add:
                        - SYS_ADMIN
                environment:
                        - TZ=Europe/Moscow
